# Generated by Django 4.1.5 on 2023-02-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_delivery_address_alter_delivery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='CVV',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='CardNum',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
    ]
