# Generated by Django 4.1.5 on 2023-02-28 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='CVV',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='CardNum',
            field=models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
