# Generated by Django 4.1.5 on 2023-02-28 19:31

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_delete_book_delete_borrowed_delete_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='expiryDate',
            field=models.CharField(max_length=5, validators=[my_app.models.expiryDate_validator]),
        ),
    ]
