# Generated by Django 4.1.5 on 2023-02-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_mymodel_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=100)),
                ('BookID', models.CharField(max_length=100)),
                ('Returned', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='ID',
        ),
    ]
