# Generated by Django 4.1.5 on 2023-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_borrowed_customers_rename_id_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='Returned',
            field=models.BooleanField(default=False),
        ),
    ]
