# Generated by Django 4.1.5 on 2023-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_borrowed_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
